# IvyeaOps one-shot install script for Windows (PowerShell 5.1+)
#
# What it does:
#   1. Checks Python 3.10+ and Node 18+ are available
#   2. Installs Python dependencies (pip)
#   3. Builds the React frontend (npm)
#   4. Generates server\.env with a random secret and an admin password hash
#   5. Prints next steps
#
# Usage (from IvyeaOps repo root):
#   powershell -ExecutionPolicy Bypass -File scripts\install.ps1
#
# Note: Run from a standard PowerShell or Windows Terminal prompt.
# Administrator is NOT required unless you want to install Python/Node.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $RepoRoot

function Write-Info($msg)  { Write-Host "[IvyeaOps] $msg" -ForegroundColor Green }
function Write-Warn($msg)  { Write-Host "[IvyeaOps] WARN: $msg" -ForegroundColor Yellow }
function Write-Fail($msg)  { Write-Host "[IvyeaOps] ERROR: $msg" -ForegroundColor Red; exit 1 }

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
Write-Info "Checking prerequisites..."

$Python = $null
foreach ($bin in @("python", "python3", "py")) {
    try {
        $ver = & $bin --version 2>&1
        if ($ver -match "Python (\d+)\.(\d+)") {
            $major = [int]$Matches[1]; $minor = [int]$Matches[2]
            if ($major -ge 3 -and $minor -ge 10) { $Python = $bin; break }
        }
    } catch {}
}
if (-not $Python) {
    Write-Fail "Python 3.10+ is required. Download from https://www.python.org/ and re-run."
}

$Node = $null
try {
    $nodeVer = & node --version 2>&1
    if ($nodeVer -match "v(\d+)") {
        if ([int]$Matches[1] -ge 18) { $Node = "node" }
    }
} catch {}
if (-not $Node) {
    Write-Fail "Node.js 18+ is required. Download from https://nodejs.org/ and re-run."
}

$npm = $null
try { $null = & npm --version 2>&1; $npm = "npm" } catch {}
if (-not $npm) { Write-Fail "npm not found. Ensure Node.js is properly installed." }

Write-Info "  Python: $(& $Python --version)"
Write-Info "  Node:   $(& node --version)"
Write-Info "  npm:    $(& npm --version)"

# ── 2. Python dependencies ────────────────────────────────────────────────────
Write-Info "Installing Python dependencies..."
Set-Location "$RepoRoot\server"
& $Python -m pip install -q -r requirements.txt
Write-Info "  Python deps installed."

# ── 3. Frontend build ────────────────────────────────────────────────────────
Write-Info "Building frontend..."
Set-Location "$RepoRoot\client"
& npm install --silent
& npm run build
Write-Info "  Frontend built into client\dist."

# ── 4. Generate server\.env ──────────────────────────────────────────────────
Set-Location "$RepoRoot\server"
$EnvFile = ".env"

if (Test-Path $EnvFile) {
    Write-Warn ".env already exists — skipping generation. Delete it and re-run to regenerate."
} else {
    Write-Info "Generating server\.env..."

    $Secret = & $Python -c "import secrets; print(secrets.token_urlsafe(32))"

    Write-Host ""
    Write-Host "  Set an admin password for the web UI."
    $SecurePw = Read-Host "  Admin password" -AsSecureString
    $Pw = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePw)
    )

    $PwHash = & $Python -c @"
import bcrypt, sys
pw = sys.argv[1].encode()
print(bcrypt.hashpw(pw, bcrypt.gensalt()).decode())
"@ $Pw

    $EnvContent = @"
# Generated by scripts\install.ps1 -- edit as needed.
# See docs\CONFIG.md for the full reference.

IVYEA_OPS_HOST=127.0.0.1
IVYEA_OPS_PORT=8001
IVYEA_OPS_DEV=0

# Session signing key (keep secret, do not change once set)
IVYEA_OPS_SECRET=$Secret

IVYEA_OPS_USER=admin
IVYEA_OPS_PASSWORD_HASH=$PwHash

# Set this to your public URL (used for CSRF protection)
IVYEA_OPS_ALLOWED_ORIGINS=http://127.0.0.1:8001
"@
    $EnvContent | Out-File -FilePath $EnvFile -Encoding utf8
    Write-Info "  server\.env created."
}

# ── 5. Ensure data directory ──────────────────────────────────────────────────
Set-Location $RepoRoot
if (-not (Test-Path "data")) { New-Item -ItemType Directory -Path "data" | Out-Null }

# ── 6. Done ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "  IvyeaOps install complete!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host ""
Write-Host "  Start the server:"
Write-Host "    cd $RepoRoot\server"
Write-Host "    $Python -m uvicorn app.main:app --host 127.0.0.1 --port 8001"
Write-Host ""
Write-Host "  Then open http://127.0.0.1:8001 in your browser."
Write-Host ""
Write-Host "  Note: Terminal features (PTY/multi-terminal) are not supported on Windows."
Write-Host "  All other features (Agent chat, settings, market data, etc.) work normally."
Write-Host ""
