#!/usr/bin/env bash
# IvyeaOps one-shot install script for Linux
#
# What it does:
#   1. Checks Python 3.9+ and Node 18+ are available
#   2. Installs Python dependencies (pip)
#   3. Builds the React frontend (npm)
#   4. Generates server/.env with a random secret and an admin password hash
#   5. Prints next steps
#
# Usage:
#   bash scripts/install.sh
#
# To run as a non-root user, make sure you have write access to the repo
# directory and that pip/npm install directories are writable.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN="\033[32m"; YELLOW="\033[33m"; RED="\033[31m"; RESET="\033[0m"
info()  { echo -e "${GREEN}[IvyeaOps]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[IvyeaOps]${RESET} $*"; }
die()   { echo -e "${RED}[IvyeaOps] ERROR${RESET} $*" >&2; exit 1; }

# ── 1. Prerequisite checks ────────────────────────────────────────────────────
info "Checking prerequisites..."

PYTHON=""
for bin in python3 python; do
  if command -v "$bin" &>/dev/null; then
    ver=$("$bin" -c "import sys; print(sys.version_info[:2])")
    major=$("$bin" -c "import sys; print(sys.version_info.major)")
    minor=$("$bin" -c "import sys; print(sys.version_info.minor)")
    if [ "$major" -gt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -ge 9 ]; }; then
      PYTHON="$bin"
      break
    fi
  fi
done
[ -n "$PYTHON" ] || die "Python 3.9+ is required. Install it with your package manager and re-run."

NODE=""
if command -v node &>/dev/null; then
  node_major=$(node -e "process.stdout.write(String(process.versions.node.split('.')[0]))")
  if [ "$node_major" -ge 18 ]; then
    NODE="node"
  fi
fi
[ -n "$NODE" ] || die "Node.js 18+ is required. Download from https://nodejs.org/ and re-run."

NPM=$(command -v npm) || die "npm not found. Ensure Node.js is properly installed."

info "  Python: $($PYTHON --version)"
info "  Node:   $(node --version)"
info "  npm:    $(npm --version)"

# ── 2. Python dependencies (in an isolated venv) ──────────────────────────────
# A venv avoids polluting system Python and, crucially, sidesteps PEP 668
# ("externally-managed-environment") which makes `pip install` into the system
# interpreter fail outright on modern Debian/Ubuntu/Fedora.
info "Creating Python virtualenv (server/.venv)..."
cd "$REPO_ROOT/server"
VENV_DIR="$REPO_ROOT/server/.venv"
if [ ! -x "$VENV_DIR/bin/python" ]; then
  if ! $PYTHON -m venv "$VENV_DIR" 2>/dev/null; then
    die "Failed to create a virtualenv. On Debian/Ubuntu install it first:
       sudo apt install python3-venv
     then re-run this script."
  fi
fi
VENV_PY="$VENV_DIR/bin/python"

info "Installing Python dependencies..."
"$VENV_PY" -m pip install -q --upgrade pip
"$VENV_PY" -m pip install -q -r requirements.txt
info "  Python deps installed into server/.venv."

# ── 3. Frontend build ────────────────────────────────────────────────────────
info "Building frontend..."
cd "$REPO_ROOT/client"
npm install --silent
npm run build
info "  Frontend built into client/dist."

# ── 4. Generate server/.env ──────────────────────────────────────────────────
cd "$REPO_ROOT/server"
ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — skipping generation. Delete it and re-run to regenerate."
else
  info "Generating server/.env..."

  SECRET=$("$VENV_PY" -c "import secrets; print(secrets.token_urlsafe(32))")

  echo ""
  echo "  Set an admin password for the web UI (press Enter to auto-generate one)."
  # Hash directly with the venv's bcrypt and capture ONLY the bare hash.
  # (Do NOT pipe `python -m app.core.hashpw` here — that helper prints
  # human-facing instructions, which would corrupt .env.)
  read -rsp "  Admin password: " PW; echo ""
  GENERATED_PW=""
  if [ -z "$PW" ]; then
    PW=$("$VENV_PY" -c "import secrets; print(secrets.token_urlsafe(9))")
    GENERATED_PW="$PW"
  fi
  PW_HASH=$("$VENV_PY" -c "import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt()).decode())" "$PW")

  # Detect public hostname (best-effort)
  HOSTNAME_GUESS=""
  if command -v hostname &>/dev/null; then
    HOSTNAME_GUESS=$(hostname -f 2>/dev/null || hostname 2>/dev/null || true)
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh — edit as needed.
# See docs/CONFIG.md for the full reference.

IVYEA_OPS_HOST=127.0.0.1
IVYEA_OPS_PORT=8001
IVYEA_OPS_DEV=0

# Session signing key (keep secret, do not change once set)
IVYEA_OPS_SECRET=${SECRET}

IVYEA_OPS_USER=admin
IVYEA_OPS_PASSWORD_HASH=${PW_HASH}

# Set this to your public URL (used for CSRF protection)
IVYEA_OPS_ALLOWED_ORIGINS=http://127.0.0.1:8001
# IVYEA_OPS_ALLOWED_ORIGINS=https://${HOSTNAME_GUESS:-ops.example.com}
EOF

  info "  server/.env created."
  if [ -n "$GENERATED_PW" ]; then
    echo ""
    warn "★ 已自动生成管理员密码：${GENERATED_PW}"
    warn "  用户名 admin，请记下来；可在网页「系统配置 → 账号安全」里修改。"
  fi
fi

# ── 5. Ensure data directory ──────────────────────────────────────────────────
cd "$REPO_ROOT"
mkdir -p data

# ── 5.5 Optional: local AI Agent (Hermes) + knowledge base (GBrain) ───────────
# Both are optional — IvyeaOps works with just the global fallback model. They
# unlock the local-tool / MCP-driven features. Official one-line installers.
echo ""
printf "  顺便安装本地 AI Agent (Hermes) + 知识库 (GBrain)？联网较慢，可跳过 (y/N) "
read -r ANS || ANS=""
if [ "$ANS" = "y" ] || [ "$ANS" = "Y" ]; then
  info "安装 Hermes Agent（官方安装器）..."
  curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash || \
    warn "Hermes 安装失败，可稍后手动重试：curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash"

  info "安装 Bun + GBrain..."
  if ! command -v bun &>/dev/null && [ ! -x "$HOME/.bun/bin/bun" ]; then
    curl -fsSL https://bun.sh/install | bash || warn "Bun 安装失败"
  fi
  BUN="$HOME/.bun/bin/bun"; [ -x "$BUN" ] || BUN="$(command -v bun || true)"
  if [ -n "$BUN" ] && [ -x "$BUN" ]; then
    "$BUN" install -g github:garrytan/gbrain || warn "GBrain 安装失败"
    GBRAIN="$HOME/.bun/bin/gbrain"
    if [ -x "$GBRAIN" ]; then
      mkdir -p "$HOME/brain"
      ( cd "$HOME/brain" && "$GBRAIN" init --pglite >/dev/null 2>&1 || true )
      info "  GBrain 安装完成（本地 PGLite，已初始化 ~/brain）。"
    fi
  else
    warn "未找到 bun，GBrain 跳过。可手动：bun install -g github:garrytan/gbrain"
  fi
  info "  安装路径会被 IvyeaOps 自动发现；如未识别，可在「系统配置 → 智能体」里填路径。"
fi

# ── 5.6 Optional: Listing 采集服务 (amazon-image-workflow, via Docker) ─────────
# Self-contained docker-compose (bundles Postgres). Free scraping (curl/puppeteer),
# no API keys. Skip if Docker is absent — Listing still works (manual + AI),
# just without auto-scrape.
if [ -f "$REPO_ROOT/amazon-image-workflow/docker-compose.yml" ]; then
  if command -v docker &>/dev/null && (docker compose version &>/dev/null || command -v docker-compose &>/dev/null); then
    echo ""
    printf "  启动 Listing 采集服务（amazon-image-workflow，Docker，免密钥）？(y/N) "
    read -r ANS2 || ANS2=""
    if [ "$ANS2" = "y" ] || [ "$ANS2" = "Y" ]; then
      info "启动采集服务（首次会构建镜像，较慢）..."
      ( cd "$REPO_ROOT/amazon-image-workflow" && (docker compose up -d --build || docker-compose up -d --build) ) \
        && info "  采集服务已启动（:3001）。IvyeaOps 默认已指向它。" \
        || warn "采集服务启动失败，可稍后手动：cd amazon-image-workflow && docker compose up -d --build"
    fi
  else
    warn "未检测到 Docker —— Listing 采集服务需要 Docker。装上 Docker 后："
    warn "  cd amazon-image-workflow && docker compose up -d --build"
    warn "（不装也行：Listing 其余功能照常，仅无法自动抓竞品。）"
  fi
fi

# ── 6. Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}  IvyeaOps install complete!${RESET}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo "  Start the server:"
echo "    cd $REPO_ROOT/server"
echo "    .venv/bin/python -m uvicorn app.main:app --host 127.0.0.1 --port 8001"
echo ""
echo "  Then open http://127.0.0.1:8001 in your browser."
echo "  A first-run wizard will guide you through agents + API keys."
echo ""
echo "  TIP: to work out of the box without a local agent CLI, set a"
echo "       「全局兜底大模型」 in 系统配置 (any OpenAI-compatible model + key)."
echo ""
echo "  For production deploy (nginx + systemd + certbot):"
echo "    See docs/INSTALL.md  (set PYTHON_BIN=server/.venv/bin/python)"
echo ""
