#!/usr/bin/env bash
# IvyeaOps one-shot install script for Linux
#
# What it does:
#   1. Checks Python 3.10+ and Node 18+ are available
#   2. Installs Python dependencies (pip)
#   3. Builds the React frontend (npm)
#   4. Generates server/.env with a random secret and an admin password hash
#   5. Prints next steps
#
# Usage:
#   bash scripts/install.sh
#
# To run as a non-root user, make sure you have write access to the repo
# directory and that pip/npm install directories are writable.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN="\033[32m"; YELLOW="\033[33m"; RED="\033[31m"; RESET="\033[0m"
info()  { echo -e "${GREEN}[IvyeaOps]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[IvyeaOps]${RESET} $*"; }
die()   { echo -e "${RED}[IvyeaOps] ERROR${RESET} $*" >&2; exit 1; }

# ── 1. Prerequisite checks ────────────────────────────────────────────────────
info "Checking prerequisites..."

PYTHON=""
for bin in python3 python; do
  if command -v "$bin" &>/dev/null; then
    ver=$("$bin" -c "import sys; print(sys.version_info[:2])")
    major=$("$bin" -c "import sys; print(sys.version_info.major)")
    minor=$("$bin" -c "import sys; print(sys.version_info.minor)")
    if [ "$major" -ge 3 ] && [ "$minor" -ge 10 ]; then
      PYTHON="$bin"
      break
    fi
  fi
done
[ -n "$PYTHON" ] || die "Python 3.10+ is required. Install it with your package manager and re-run."

NODE=""
if command -v node &>/dev/null; then
  node_major=$(node -e "process.stdout.write(String(process.versions.node.split('.')[0]))")
  if [ "$node_major" -ge 18 ]; then
    NODE="node"
  fi
fi
[ -n "$NODE" ] || die "Node.js 18+ is required. Download from https://nodejs.org/ and re-run."

NPM=$(command -v npm) || die "npm not found. Ensure Node.js is properly installed."

info "  Python: $($PYTHON --version)"
info "  Node:   $(node --version)"
info "  npm:    $(npm --version)"

# ── 2. Python dependencies ────────────────────────────────────────────────────
info "Installing Python dependencies..."
cd "$REPO_ROOT/server"
$PYTHON -m pip install -q -r requirements.txt
info "  Python deps installed."

# ── 3. Frontend build ────────────────────────────────────────────────────────
info "Building frontend..."
cd "$REPO_ROOT/client"
npm install --silent
npm run build
info "  Frontend built into client/dist."

# ── 4. Generate server/.env ──────────────────────────────────────────────────
cd "$REPO_ROOT/server"
ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — skipping generation. Delete it and re-run to regenerate."
else
  info "Generating server/.env..."

  SECRET=$($PYTHON -c "import secrets; print(secrets.token_urlsafe(32))")

  echo ""
  echo "  Set an admin password for the web UI."
  echo "  (Input is hidden)"
  PW_HASH=$($PYTHON -m app.core.hashpw 2>/dev/null) || {
    # Fallback: prompt manually then hash inline
    read -rsp "  Admin password: " PW; echo ""
    PW_HASH=$($PYTHON -c "import bcrypt,sys; print(bcrypt.hashpw(sys.argv[1].encode(), bcrypt.gensalt()).decode())" "$PW")
  }

  # Detect public hostname (best-effort)
  HOSTNAME_GUESS=""
  if command -v hostname &>/dev/null; then
    HOSTNAME_GUESS=$(hostname -f 2>/dev/null || hostname 2>/dev/null || true)
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh — edit as needed.
# See docs/CONFIG.md for the full reference.

IVYEA_OPS_HOST=127.0.0.1
IVYEA_OPS_PORT=8001
IVYEA_OPS_DEV=0

# Session signing key (keep secret, do not change once set)
IVYEA_OPS_SECRET=${SECRET}

IVYEA_OPS_USER=admin
IVYEA_OPS_PASSWORD_HASH=${PW_HASH}

# Set this to your public URL (used for CSRF protection)
IVYEA_OPS_ALLOWED_ORIGINS=http://127.0.0.1:8001
# IVYEA_OPS_ALLOWED_ORIGINS=https://${HOSTNAME_GUESS:-ops.example.com}
EOF

  info "  server/.env created."
fi

# ── 5. Ensure data directory ──────────────────────────────────────────────────
cd "$REPO_ROOT"
mkdir -p data

# ── 6. Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}  IvyeaOps install complete!${RESET}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo "  Start the server:"
echo "    cd $REPO_ROOT/server"
echo "    $PYTHON -m uvicorn app.main:app --host 127.0.0.1 --port 8001"
echo ""
echo "  Then open http://127.0.0.1:8001 in your browser."
echo ""
echo "  For production deploy (nginx + systemd + certbot):"
echo "    See docs/INSTALL.md"
echo ""
